services:
  app:
    image: ghcr.io/xlair-dev/xlair.dev:latest@sha256:e67567eb2ac755a2f223336b5b29842896f121af75d91efa8a453dd29c8aea60
    container_name: xlair-dev
    ports:
      - "${HOST_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
