services:
  app:
    image: ghcr.io/xlair-dev/xlair.dev:latest@sha256:18983df3e150754b82ef35def756557532e2b35cda4d737b09b617e86ced1d32
    container_name: xlair-dev
    ports:
      - "${HOST_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
