services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xlair-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
