services:
  app:
    image: ghcr.io/xlair-dev/xlair.dev:latest
    container_name: xlair-dev
    ports:
      - "${HOST_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
