services:
  app:
    image: ghcr.io/xlair-dev/xlair.dev:latest@sha256:6e982215900854b8ea3c8ab63a35ffbcf23cead3def9fc6d5ef828666c018d32
    container_name: xlair-dev
    ports:
      - "${HOST_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
